# Generated by Django 4.1.7 on 2023-06-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(max_length=5)),
                ('Producto', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField(max_length=5)),
                ('Unidad', models.CharField(max_length=2)),
                ('Precio', models.IntegerField(max_length=5)),
            ],
        ),
    ]
