# Generated by Django 4.1.7 on 2023-06-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.CharField(max_length=20)),
                ('NombreContacto', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=20)),
                ('Ciudad', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.CharField(max_length=20)),
                ('Pago', models.CharField(max_length=20)),
                ('DiaEntregas', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='Proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedores'),
            preserve_default=False,
        ),
    ]
