# Generated by Django 4.1.7 on 2023-06-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_proveedores_correo_alter_proveedores_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='artLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(max_length=5)),
                ('Producto', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField(max_length=5)),
                ('Unidad', models.CharField(max_length=2)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedores')),
            ],
        ),
    ]
