# Generated by Django 4.1.7 on 2023-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_artlimpieza'),
    ]

    operations = [
        migrations.CreateModel(
            name='artHabitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(max_length=5)),
                ('Producto', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField(max_length=5)),
            ],
        ),
    ]
