# Generated by Django 4.1.7 on 2023-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_arthabitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Unidad',
            field=models.IntegerField(choices=[[0, 'G'], [1, 'DG'], [2, 'HG'], [3, 'KG'], [4, 'DC'], [5, 'CG'], [6, 'MG']]),
        ),
    ]
