# Generated by Django 4.1.7 on 2023-06-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_alter_stock_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Unidad',
            field=models.IntegerField(choices=[[0, 'Gramos'], [1, 'Decagramos'], [2, 'Hectogramos'], [3, 'Kilogramos'], [4, 'Decigramos'], [5, 'Centigramos'], [6, 'Miligramo']]),
        ),
    ]
