# Generated by Django 4.1.7 on 2023-06-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_stock_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Unidad',
            field=models.IntegerField(choices=[[0, 'G'], [1, 'KG'], [2, 'Miligramo']]),
        ),
    ]
