# Generated by Django 4.1.7 on 2023-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_alter_artlimpieza_unidad_alter_stock_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artlimpieza',
            name='Unidad',
            field=models.IntegerField(blank=True, choices=[[0, 'Gramos'], [1, 'Kilogramos'], [2, 'Miligramos'], [3, 'Litros']]),
        ),
    ]
