# Generated by Django 4.1.7 on 2023-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_alter_proveedores_diaentregas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
    ]
