# Generated by Django 4.1.7 on 2023-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0015_alter_proveedores_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='Pago',
            field=models.IntegerField(choices=[[0, 'Bolivares'], [1, 'Dolares'], [2, 'Pago Movil'], [3, 'Pesos Colombianos']]),
        ),
    ]
