# Generated by Django 4.1.7 on 2023-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0016_alter_proveedores_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artlimpieza',
            name='Unidad',
            field=models.IntegerField(choices=[[0, 'Gramos'], [1, 'Litros'], [2, 'Ninguna de las anteriores']]),
        ),
    ]
