# Generated by Django 4.1.7 on 2023-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0017_alter_artlimpieza_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artlimpieza',
            name='Unidad',
            field=models.IntegerField(choices=[[0, 'Gramos'], [1, 'Kilogramos'], [2, 'Litros'], [3, 'Ninguna de las anteriores']]),
        ),
    ]
