# Generated by Django 4.1.7 on 2023-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0018_alter_artlimpieza_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Tipo',
            field=models.IntegerField(choices=[[0, 'Granos'], [1, 'Verduras'], [2, 'Frutas'], [3, 'Prod. Lacteos'], [4, 'Proteinas'], [5, 'Carne']], default=1),
            preserve_default=False,
        ),
    ]
