# Generated by Django 4.1.7 on 2023-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=20)),
                ('Descripcion', models.TextField()),
                ('TipoProducto', models.IntegerField(choices=[[0, 'Desayuno'], [1, 'Almuerzo'], [2, 'Postre'], [3, 'Bebida'], [4, 'Cena']])),
                ('Precio', models.IntegerField()),
                ('Imagen', models.ImageField(null=True, upload_to='restaurante')),
            ],
        ),
    ]
