# Generated by Django 4.1.7 on 2023-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Cedula', models.CharField(max_length=8)),
                ('Telefono', models.CharField(max_length=15)),
                ('Experiencia', models.TextField()),
                ('Clasificacion', models.IntegerField(blank=True, choices=[[0, '★'], [1, '★★'], [2, '★★★'], [3, '★★★★'], [4, '★★★★★']])),
            ],
        ),
    ]
