# Generated by Django 4.1.7 on 2023-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sugerencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencias',
            name='Telefono',
            field=models.CharField(max_length=11),
        ),
    ]
