# Generated by Django 4.2.2 on 2023-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=11)),
                ('correo', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
