# Generated by Django 4.2.2 on 2023-06-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Huespedes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='id_huesped',
            new_name='codigo',
        ),
    ]
