# Generated by Django 4.2.2 on 2023-07-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_pers', models.PositiveIntegerField()),
                ('nombre_c', models.CharField(max_length=15)),
                ('categoria', models.TextField(null=True)),
                ('precioxdia', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('estatus_categ', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
