# Generated by Django 4.2.2 on 2023-07-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('id_num_habitaciones', models.BigAutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=False)),
                ('numero_habitacion', models.PositiveIntegerField(null=True)),
                ('estatus_habi', models.PositiveIntegerField(null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.categorias')),
            ],
        ),
    ]
