# Generated by Django 4.2.2 on 2023-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
