# Generated by Django 4.2.2 on 2023-07-09 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitaciones', '0002_habitaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_entrada', models.DateField()),
                ('f_salida', models.DateField()),
                ('num_personas', models.PositiveIntegerField()),
                ('num_niños', models.PositiveIntegerField()),
                ('num_habi_solicitadas', models.PositiveIntegerField(null=True)),
                ('estatus_datos_rese', models.PositiveIntegerField(null=True)),
                ('dias_pago', models.PositiveIntegerField(null=True)),
                ('n_ocupante', models.CharField(max_length=25, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='metodos_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=25)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_r', models.CharField(max_length=25)),
                ('apellido_r', models.CharField(max_length=25)),
                ('telefono', models.PositiveIntegerField()),
                ('tarifa_pago', models.PositiveIntegerField(null=True)),
                ('fecha_reserva', models.DateField(null=True)),
                ('hora_de_llegada', models.TimeField(null=True)),
                ('estatus_reservacion', models.PositiveIntegerField(null=True)),
                ('peticiones', models.CharField(max_length=250, null=True)),
                ('Forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.metodos_pagos')),
                ('id_datos_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.datos_reserva')),
                ('id_num_habitaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitaciones')),
            ],
        ),
    ]
