# Generated by Django 4.2.2 on 2023-07-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitaciones'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_reserva',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitaciones.categorias'),
        ),
    ]
